### ISSUE TITLE
Bugs: hide-and-seek

### ISSUE THREAD

**Issue by Banstein** [VSeray/Portfolio#16]
Hi @VSeray,

- [x]  While I was looking on your code I found a bug in your data.js file line 11, there was an undefined variable

- [x] Kindly ensure to fix  variable Json to JSON

- [x] Please check this [link](https://github.com/VSeray/Portfolio/blob/hide-and-seek/data.js#L11)

**Comment by VSeray** [comment]
Hey @Banstein ,

Thank you for pointing out that issue, I have resolved the issue.
