### ISSUE TITLE
Morning Session

### ISSUE THREAD

**Issue by HAMMAS-SALEEM** [VSeray/Portfolio#8]
I know you worked hard on your project but you still need to stick with the Figma template. But it's a good project for the first time so keep working.

**Comment by jaflih** [comment]
Great job!  
I recommend you to follow the design on Figma more thoroughly ( width, margin ... )

**Comment by matovu-farid** [comment]
Great work here 🥇 .  I love your implementation. Although in future, you could use pseudo-classes to select even and odd elements for positioning the images with their respective order Id. This will make your code more extensible 💯  so that you can add future projects worked on.
